spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: admin
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: always

  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/

  resources:
    static-locations: file:src/main/resources/static/
    cache:
      period: 0